# Deploy a static HTML site to Azure Web App

name: Deploy static site to Azure Web App - sarfraz-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E16411A1EC76411EBAE7C925B0F55B4B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1DE6F4FD03B04B049C4FB095997F663E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ED533967C42E4A8ABFE06D462F1D5CF6 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sarfraz-web'
          package: '.'
          